

let arr = ['a', 'A', 'b', 'Z', 'c', 'd', 'X', 'e', 'N', 'f', 'g']


//task 1 - arr traverse

//task2 - small - capital - upper case 

//map method

//upper case 



// arr.map(function fun(maal) {
//     // console.log(maal);
//     console.log(maal.toUpperCase());

// })

// let ans=arr.filter(maal=>{
//     return maal==maal.toUpperCase();
// })
// console.log(ans);


//?:

// let ans = arr.filter(maal => maal === maal.toUpperCase() ? true : maal===maal.toLowerCase());
// console.log(ans);






let array=[10,20,30,40,50,60,70,80,3,4,3,4,3,3,4,3,10,20,30];
console.log(array.pop());
console.log(array);

array.push(1000)
console.log(array);

array.shift()
console.log(array);

array.unshift(5000);
console.log(array);

// console.log(array.__proto__);


let response=array.includes(30);
console.log(response);

console.log(array.includes(1000));

console.log(array.indexOf(40));

console.log(array.lastIndexOf(3));
console.log(array.indexOf(3));

console.log(array.indexOf("vikas"));

//slice

// console.log(array.slice(2,8));
console.log("---------------");
// console.log(array.slice(-2,6));
// console.log(array.slice(,9));
console.log(array.slice(-5,-2));











































